# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinax_images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSpotting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_type', models.CharField(max_length=100)),
                ('image_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pinax_images.ImageSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'cloud_type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cloudspotting',
            unique_together=set([('cloud_type', 'user')]),
        ),
    ]
